FROM golang:1.23-alpine AS build
ARG TARGETOS
ARG TARGETARCH
WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY cmd ./cmd
COPY internal ./internal
RUN CGO_ENABLED=0 GOOS=$TARGETOS GOARCH=$TARGETARCH go build -trimpath -ldflags="-s -w" -o /out/ondc-network ./cmd/ondc-network

FROM gcr.io/distroless/static-debian12:nonroot
COPY --from=build /out/ondc-network /usr/local/bin/ondc-network
EXPOSE 3030 4030 5001 5002 6001 6002 6101 6102
VOLUME ["/var/lib/ondc-network"]
ENTRYPOINT ["/usr/local/bin/ondc-network"]
