import assert from "node:assert/strict";
import { test } from "node:test";
import { fileURLToPath } from "node:url";

import { openReservedDatabase } from "../../src/reserved/db.js";
import { FixtureReservedSource } from "../../src/reserved/fixture.js";
import { HttpFleetManifestPublisher } from "../../src/reserved/fleetManifest.js";
import { ReservedOrderService } from "../../src/reserved/order.js";
import { ReservedStore } from "../../src/reserved/store.js";
import { reservedOrderRequest } from "../helpers.js";
import {
  FLEET_SIM_ABSENT_MESSAGE,
  fleetSimRepoPath,
  fleetSimRepoPresent,
  startFleetSim,
  type RunningFleetSim,
} from "./fleetSimHarness.js";

/**
 * The same seam as fleetManifestIntegration.test.ts (confirm publishes a
 * seat count to the sibling simulator's PUT /fleet/manifest, and it reads
 * back through /fleet/duty + /fleet/resolve), proven for a second corridor:
 * Bengaluru-Mangaluru (KA-BNG-MNG in Tatak, BNG-MNG in the simulator's own
 * corridor ids). "0700BNGMNG" is a real, non-ambiguous KSRTC service number
 * both repositories carry - this provider's own fixtures (generated by
 * scripts/generate-ksrtc-fixtures.ts from Tatak's corridor data) and the
 * simulator's own corridor-roster.json (generated by its
 * scripts/build-corridor-roster.ts from the same Tatak source).
 *
 * Skips, rather than fails, when the sibling repository is not checked out
 * locally - see fleetSimHarness.ts.
 */

const REPO = fleetSimRepoPath();
const PRESENT = fleetSimRepoPresent();

if (!PRESENT) {
  console.warn(FLEET_SIM_ABSENT_MESSAGE(REPO));
}

const fixtureRoot = fileURLToPath(new URL("../../fixtures", import.meta.url));
const migrationRoot = fileURLToPath(new URL("../../migrations/reserved", import.meta.url));
const source = await FixtureReservedSource.load(fixtureRoot, "ksrtc");

const SERVICE_ID = "0700BNGMNG";
const TRAVEL_DATE = "2026-09-15";
const ITEM = `RSV-${SERVICE_ID}-${TRAVEL_DATE}-AIRAVAT_CLUB_CLASS`;
/** 05:30 IST, well before the 07:00 IST departure and inside the booking window. */
const BPP_NOW = Date.parse("2026-09-15T00:00:00.000Z");
/** 10:30 IST, partway through the scheduled 07:00-14:30 IST run. */
const SIM_CLOCK_INSTANT = "2026-09-15T05:00:00.000Z";
const MANIFEST_TOKEN = "fleet-manifest-integration-mangaluru-test-token";

const PASSENGERS = [
  { seatId: "13A", name: "A Passenger", age: 40, gender: "male" as const },
  { seatId: "13B", name: "B Passenger", age: 38, gender: "female" as const },
];

async function readManifest(
  simUrl: string,
  serviceId: string,
  travelDate: string,
): Promise<{ seatsBooked: number; seatsTotal: number } | undefined> {
  const duty = (await (
    await fetch(`${simUrl}/fleet/duty?service=${serviceId}&date=${travelDate}`)
  ).json()) as {
    assignment: { status: string };
    vehicle: { bin: string } | null;
  };
  assert.ok(
    duty.vehicle?.bin,
    `expected /fleet/duty to disclose a vehicle for ${serviceId}/${travelDate}; got assignment ${JSON.stringify(duty.assignment)}`,
  );
  const resolved = (await (
    await fetch(`${simUrl}/fleet/resolve?code=${duty.vehicle.bin}&entry=manual`)
  ).json()) as {
    duty: { reservation?: { required: boolean; manifest?: { seatsBooked: number; seatsTotal: number } } };
  };
  return resolved.duty.reservation?.manifest;
}

test(
  "a confirm on Bengaluru-Mangaluru publishes to, and reads back from, the real fleet simulator",
  { skip: PRESENT ? false : FLEET_SIM_ABSENT_MESSAGE(REPO) },
  async () => {
    let sim: RunningFleetSim | null = null;
    try {
      sim = await startFleetSim({
        env: {
          MANIFEST_TOKEN,
          SIM_CLOCK: SIM_CLOCK_INSTANT,
          INTERCITY_MANIFEST_MAX_AGE_SECONDS: "604800",
          INTERCITY_CORRIDORS: "BNG-HSP,BNG-MNG",
        },
      });
      assert.ok(sim, "the fleet simulator did not start");

      const publisher = new HttpFleetManifestPublisher({
        url: sim.url,
        token: MANIFEST_TOKEN,
        ttlSeconds: 3600,
      });

      let counter = 0;
      const idFactory = () => `${String((counter += 1)).padStart(8, "0")}-fixed`;
      const store = new ReservedStore(openReservedDatabase({ url: ":memory:", migrationRoot }), {
        idFactory,
      });
      const events: Record<string, unknown>[] = [];
      const orders = new ReservedOrderService(
        "ksrtc",
        source,
        {
          subscriberId: "ksrtc.provider.example.test",
          subscriberUri: "https://ksrtc-network.example.test",
        },
        store,
        {
          publicBaseUrl: "https://provider.example.test",
          reservation: {
            closeMinutes: 45,
            horizonDays: 30,
            occupancySeed: 20_260_905,
            holdTtlSeconds: 600,
            manifestRetentionDays: 30,
          },
          now: () => new Date(BPP_NOW),
          idFactory,
          fleetManifest: publisher,
          eventLogger: (fields) => events.push(fields),
        },
      );

      await orders.select(
        reservedOrderRequest("select", {
          itemId: ITEM,
          seatIds: PASSENGERS.map((p) => p.seatId),
          fromBoardingPointId: "BP-BLR-MAJESTIC",
          toBoardingPointId: "BP-MNG-MANGALURU",
        }) as never,
      );
      const confirmed = await orders.confirm(
        reservedOrderRequest("confirm", {
          itemId: ITEM,
          seatIds: PASSENGERS.map((p) => p.seatId),
          manifest: PASSENGERS,
          fromBoardingPointId: "BP-BLR-MAJESTIC",
          toBoardingPointId: "BP-MNG-MANGALURU",
        }) as never,
      );
      assert.ok((confirmed.order as { id: string }).id, "confirm did not return an order id");

      const manifest = await readManifest(sim.url, SERVICE_ID, TRAVEL_DATE);
      assert.ok(manifest, "expected a manifest after confirm");
      assert.equal(manifest!.seatsBooked, 2);
      assert.equal(manifest!.seatsTotal, 53);
      assert.deepEqual(
        events.filter((event) => event.outcome === "FAILED"),
        [],
        "the confirm push must not fail against a running simulator",
      );

      store.close();
    } finally {
      await sim?.stop();
    }
  },
);
