import { fileURLToPath } from "node:url";

import { openReservedDatabase } from "../../src/reserved/db.js";
import { RESERVED_DOMAIN, RESERVED_VERSION } from "../../src/reserved/domain.js";
import { ReservedLifecycleError } from "../../src/reserved/errors.js";
import { FixtureReservedSource } from "../../src/reserved/fixture.js";
import { ReservedOrderService } from "../../src/reserved/order.js";
import { ReservedStore } from "../../src/reserved/store.js";
import {
  reservedCancelRequest,
  reservedOrderRequest,
  reservedSearchRequest,
  reservedStatusRequest,
} from "../helpers.js";

/**
 * One booking, start to finish, with every clock and every id held still.
 *
 * Two callers share this: the golden-file test, which compares what it
 * produces against payloads checked into the repository, and the script that
 * writes those payloads in the first place. Keeping them on one code path is
 * the point, because a golden file generated by different code from the code
 * under test proves nothing.
 *
 * The golden files are a weaker guard than the contract tests the two existing
 * categories have, and the weakness is worth naming rather than glossing: those
 * assert that generated payloads share a key structure with a published
 * specification's own example files, which is what stops a build drifting into
 * something that merely looks like the protocol it claims. This category has no
 * published examples to test against, because it publishes under a local domain
 * that claims conformance to nothing. So these files catch drift from the
 * document that specified them and cannot catch drift from a specification that
 * does not exist yet.
 */

const fixtureRoot = fileURLToPath(new URL("../../fixtures", import.meta.url));
const migrationRoot = fileURLToPath(
  new URL("../../migrations/reserved", import.meta.url),
);

export const GOLDEN_TRAVEL_DATE = "2026-09-30";
export const GOLDEN_ITEM = `RSV-2259BNGHMP-${GOLDEN_TRAVEL_DATE}-PALLAKKI`;
export const GOLDEN_NOW = Date.parse("2026-09-20T10:00:00.000Z");

function callbackContext(action: string) {
  return {
    domain: RESERVED_DOMAIN,
    location: { country: { code: "IND" }, city: { code: "std:080" } },
    action: `on_${action}`,
    version: RESERVED_VERSION,
    bap_id: "bap.example.test",
    bap_uri: "https://bap.example.test",
    bpp_id: "ksrtc.provider.example.test",
    bpp_uri: "https://ksrtc-network.example.test",
    transaction_id: "0b0e1f6a-5c47-4d19-9a2f-3c8b1d6e7f01",
    message_id: "7d3f2c81-4a6b-4f0e-8c15-2b9d7e4a6c33",
    timestamp: new Date(GOLDEN_NOW).toISOString(),
    ttl: "PT30S",
  };
}

function envelope(action: string, message: Record<string, unknown>) {
  return { context: callbackContext(action), message };
}

function errorEnvelope(action: string, error: ReservedLifecycleError) {
  const attachment = error.attachment ?? {};
  const message: Record<string, unknown> = {};
  if (attachment.seatMap) message.tags = [attachment.seatMap];
  if (attachment.tags) message.tags = attachment.tags;
  if (attachment.refund) message.refund = attachment.refund;
  return {
    context: callbackContext(action),
    message,
    error: { code: error.code, message: error.message },
  };
}

export type GoldenPayloads = Record<string, Record<string, unknown>>;

export async function runGoldenLifecycle(): Promise<GoldenPayloads> {
  const source = await FixtureReservedSource.load(fixtureRoot, "ksrtc");
  const clock = { at: GOLDEN_NOW };
  let counter = 0;
  const idFactory = () => `${String((counter += 1)).padStart(8, "0")}-fixed`;
  const store = new ReservedStore(
    openReservedDatabase({ url: ":memory:", migrationRoot }),
    { idFactory },
  );
  const orders = new ReservedOrderService(
    "ksrtc",
    source,
    {
      subscriberId: "ksrtc.provider.example.test",
      subscriberUri: "https://ksrtc-network.example.test",
    },
    store,
    {
      publicBaseUrl: "https://provider.example.test",
      reservation: {
        closeMinutes: 45,
        horizonDays: 30,
        occupancySeed: 20_260_905,
        holdTtlSeconds: 600,
        manifestRetentionDays: 30,
      },
      now: () => new Date(clock.at),
      idFactory,
    },
  );

  const manifest = [
    { seatId: "U3A", name: "A Passenger", age: 34, gender: "female" },
    { seatId: "U3B", name: "B Passenger", age: 36, gender: "male" },
  ];
  const seatIds = ["U3A", "U3B"];
  const payloads: GoldenPayloads = {};

  payloads.on_search = envelope(
    "search",
    await orders.search(
      reservedSearchRequest({ travelDate: GOLDEN_TRAVEL_DATE }) as never,
    ),
  );
  payloads.on_select_browse = envelope(
    "select",
    await orders.select(
      reservedOrderRequest("select", { itemId: GOLDEN_ITEM }) as never,
    ),
  );
  payloads.on_select_seats = envelope(
    "select",
    await orders.select(
      reservedOrderRequest("select", { itemId: GOLDEN_ITEM, seatIds }) as never,
    ),
  );
  try {
    await orders.select(
      reservedOrderRequest("select", {
        itemId: GOLDEN_ITEM,
        seatIds: ["L1A"],
        transactionId: "tx-unlucky",
      }) as never,
    );
  } catch (error) {
    payloads.on_select_unavailable = errorEnvelope(
      "select",
      error as ReservedLifecycleError,
    );
  }
  payloads.on_init = envelope(
    "init",
    await orders.init(
      reservedOrderRequest("init", {
        itemId: GOLDEN_ITEM,
        seatIds,
        manifest,
      }) as never,
    ),
  );
  const confirmed = await orders.confirm(
    reservedOrderRequest("confirm", {
      itemId: GOLDEN_ITEM,
      seatIds,
      manifest,
    }) as never,
  );
  payloads.on_confirm = envelope("confirm", confirmed);
  const orderId = (confirmed.order as { id: string }).id;
  payloads.on_status = envelope(
    "status",
    orders.status(reservedStatusRequest({ orderId }) as never),
  );
  const quoted = await orders.cancel(
    reservedCancelRequest({
      orderId,
      code: "SOFT_CANCEL",
      seatIds: ["U3B"],
    }) as never,
  );
  payloads.on_cancel_quote = envelope("cancel", quoted);
  const quoteId = (
    (quoted.tags as Array<{
      descriptor: { code: string };
      list: Array<{ descriptor: { code: string }; value: string }>;
    }>)[0].list.find((entry) => entry.descriptor.code === "REFUND_QUOTE_ID")!
  ).value;
  payloads.on_cancel_committed = envelope(
    "cancel",
    await orders.cancel(
      reservedCancelRequest({
        orderId,
        code: "CONFIRM_CANCEL",
        seatIds: ["U3B"],
        quoteId,
      }) as never,
    ),
  );
  store.close();
  return payloads;
}
