server:
  port: 6002
cache:
  host: sync-redis
  port: 6379
  ttl: PT10M
  db: 1
client:
  webhook:
    url: http://bmtc-sandbox:3000/mobility/search
app:
  mode: bpp
  gateway:
    mode: network
    inboxQueue: bmtc-inbox
    outboxQueue: bmtc-outbox
    amqpURL: amqp://beckn:beckn123@sync-rabbitmq:5672
  actions:
    requests:
      search:
        ttl: PT4S
    responses:
      on_search:
        ttl: PT4S
  privateKey: RUNTIME_PRIVATE_KEY
  publicKey: RUNTIME_PUBLIC_KEY
  subscriberId: bmtc.bpp.transit.localhost
  subscriberUri: http://bmtc-bpp-network:6002
  registryUrl: http://registry:3030/subscribers
  auth: true
  uniqueKey: bmtc-bpp-key
  city: std:080
  country: IND
  ttl: PT10M
  httpTimeout: PT3S
  httpRetryCount: 2
  telemetry:
    enabled: false
    url: ""
    batchSize: 100
    syncInterval: 30
    redis_db: 3
  useLayer2Config: false
  mandateLayer2Config: false
