server:
  port: 6202
cache:
  host: sync-redis
  port: 6379
  ttl: PT10M
  db: 1
client:
  webhook:
    url: http://transit-bpp:7001/ksrtc/inbound
app:
  mode: bpp
  gateway:
    mode: network
    inboxQueue: ksrtc-inbox
    outboxQueue: ksrtc-outbox
    amqpURL: amqp://beckn:beckn123@sync-rabbitmq:5672
  actions:
    requests:
      search:
        ttl: PT4S
      select:
        ttl: PT4S
      init:
        ttl: PT4S
      confirm:
        ttl: PT4S
      status:
        ttl: PT4S
      cancel:
        ttl: PT4S
    responses:
      on_search:
        ttl: PT4S
      on_select:
        ttl: PT4S
      on_init:
        ttl: PT4S
      on_confirm:
        ttl: PT4S
      on_status:
        ttl: PT4S
      on_cancel:
        ttl: PT4S
  privateKey: RUNTIME_PRIVATE_KEY
  publicKey: RUNTIME_PUBLIC_KEY
  subscriberId: ksrtc.bpp.transit.localhost
  subscriberUri: http://ksrtc-bpp-network:6202
  registryUrl: http://registry:3030/subscribers
  auth: true
  uniqueKey: ksrtc-bpp-key
  city: std:080
  country: IND
  ttl: PT10M
  httpTimeout: PT3S
  httpRetryCount: 2
  openAPIValidator:
    cachedFileLimit: 4
  telemetry:
    enabled: false
    url: ""
    batchSize: 100
    syncInterval: 30
    redis_db: 3
  useLayer2Config: false
  mandateLayer2Config: false
